### ISSUE TITLE
WPlainPanel does not resize properly

### ISSUE THREAD

**Issue by Gavintime** [CottonMC/LibGui#53] opened 2020-05-04 15:13 UTC
**Describe the bug**
Item slot widgets cause its parent WPlainPanel to have extra padding on the right side and bottom of the screen compared to vanilla UI.

**To Reproduce**
1. Create a new object from a class that extends CottonCraftingController
2. Create a WPlainPanel and set it as the root panel
3. Add a WItemSlot at 0,0 to the WPlainPanel

**Expected behavior**
All sides of the ui should have the same amount of spacing to match vanilla UIs such as the chest ui.

**Screenshots**
LibGUI
![image](https://user-images.githubusercontent.com/16593223/80981302-caf95d80-8df7-11ea-8a69-08fd84ddafd5.png)

A vanilla chest
![image](https://user-images.githubusercontent.com/16593223/80981418-efedd080-8df7-11ea-8912-5cbcdf5c7ba7.png)

**Version of the:**
 - LibGUI 1.8.2+1.15.2
 - Fabric API 0.7.1+build.301-1.15
 - Minecraft 1.15.2

**Comment by Juuxel** [comment] 2020-05-20 22:51
This was caused by item slots being offset one pixel to the left and up, fixed in 2.0 (d25e1c4).

**Closed by Juuxel** 2020-05-20 22:51 UTC
Labels: bug
