### ISSUE TITLE
Support for accessibility keyboard control

### ISSUE THREAD

**Issue by Boundarybreaker** [CottonMC/LibGui#54] opened 2020-05-11 04:20 UTC
Right now, LibGui doesn't have support for keyboard control of menus - using tab or shift+tab to move between buttons/sliders, space to interact with a button, and left/right to move sliders. This is pretty crucial for accessibility options. Vanilla screens do this through the `changeFocus` methods on both screens and buttons, and the `keyPressed` method on elements (buttons and sliders). It should hopefully not be too difficult to add support for these in with default implementations, but I'd have to try it myself to fully know.

**Comment by Juuxel** [comment] 2020-05-11 04:57
(Partially) duplicate of #37.

**Comment by Boundarybreaker** [comment] 2020-05-11 04:57
oh yeah, it is oops ^^;

**Comment by Juuxel** [comment] 2020-05-11 05:41
> left/right to move sliders

Done already (though you have to click first until we have cycling).

> space to interact with a button

Easy to implement, though not visible until widget cycling is implemented.

> using tab or shift+tab to move between buttons/sliders

This one is going to be a bit tricky to implement since there's no global child list in LibGui unlike in vanilla (`Screen.children`).

**Comment by Juuxel** [comment] 2020-05-20 22:50
Added in 2.0.

**Closed by Juuxel** 2020-05-20 22:50 UTC
Labels: enhancement
